# Generated by Django 4.2.2 on 2023-07-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_subscribedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
